### ISSUE TITLE
Tagging released version

### ISSUE THREAD

**Issue by manhthiep** [iDoraemon/BiBo-Kit---Panorama#1]
Các chú tag hộ anh các phiên bản stable để dễ lấy về nhé.

**Comment by nvkhoi** [comment]
OK anh, nhưng chưa chắc đã hoàn thiện nên em để là Release Candidate ạ.

Nguyễn Văn Khôi - Lớp CS0801 - SE61174

Vào 23:05 Ngày 20 tháng 04 năm 2015, Manh Thiep Nguyen <
notifications@github.com> đã viết:
