### ISSUE TITLE
Sao lại bỏ các namespace trong khai báo class trong Stitcher.cpp

### ISSUE THREAD

**Issue by manhthiep** [iDoraemon/BiBo-Kit---Panorama#2]
Anh thấy không hợp lý lắm khi bỏ namespace trong Stitcher.cpp,
bởi vì như thế không biết được class nào nằm trong namespace nào luôn, khó tra cứu.

Để như cũ vẫn hay hơn.

**Comment by nvkhoi** [comment]
OK anh, em thêm đầy đủ namespace rồi ạ.

Nguyễn Văn Khôi - Lớp CS0801 - SE61174

Vào 23:28 Ngày 20 tháng 04 năm 2015, Manh Thiep Nguyen <
notifications@github.com> đã viết:
