### ISSUE TITLE
Check pairwise.txt exists

### ISSUE THREAD

**Issue by manhthiep** [iDoraemon/BiBo-Kit---Panorama#5]
Stitcher.cpp không thèm check xem là pairwise.txt có tồn tại hay không.

**Comment by manhthiep** [comment]
Sử dụng file pairwise.txt để set các file đầu vào cũng được, nhưng nếu không có pairwise.txt thì:
1. phải kết thúc ngay và báo lỗi.
2. hoặc scan cả thư mục và stitch mà không có pairwise

Anh prefer cách 1 hơn.

**Comment by nvkhoi** [comment]
Giải pháp 2 em có làm rồi (hàm feed đóng trong comment). Hôm qua anh nói
thế làm em tưởng mọi thứ nhập từ pairwise.txt hết :v
OK để em thêm.

Nguyễn Văn Khôi - Lớp CS0801 - SE61174

Vào 09:44 Ngày 21 tháng 04 năm 2015, Manh Thiep Nguyen <
notifications@github.com> đã viết:

**Comment by nvkhoi** [comment]
Anh kiểm tra Git nhé. Do chỉ copy/paste một chút thôi nên em ko tạo release

**Comment by nvkhoi** [comment]
À quên anh cần thêm bộ test nào ko để em biết mà làm lại mớ pairwise.txt

**Comment by nvkhoi** [comment]
Rồi anh nhé. Anh kiểm tra Git. Em ko làm release.
Anh cần bộ test nào nữa ko để em làm lại mớ pairwise.txt

Nguyễn Văn Khôi - Lớp CS0801 - SE61174

Vào 10:01 Ngày 21 tháng 04 năm 2015, Văn Khôi, Nguyễn <
khoinvse61174@fpt.edu.vn> đã viết:

**Comment by manhthiep** [comment]
Chắc không cần test mới đâu, bên em cập nhật lại các mẫu trước đây của em mà test lại xem.
